### PR TITLE
update base position notional in genesis.sh

### PR DESCRIPTION
**Pull request by yujin512**
update the genesis.sh file to reflect recommendation on the base position notional values for midcap and long tail liquidity tiers  https://dydx-team.slack.com/archives/C04BNGM82HM/p1697493986734849?thread_ts=1697487833.033209&cid=C04BNGM82HM

### CODE REVIEW

**Review by IvoCrnkovic — APPROVED** [review]
lgtm!

just to be sure, there's no other place these changes have to be reflected? I don't think this appears in `sample_pregenesis.json`

**Comment by yujin512** [comment]
> lgtm!
> 
> just to be sure, there's no other place these changes have to be reflected? I don't think this appears in `sample_pregenesis.json`

yeah I think pregenesis.sh reads from genesis.sh, and genesis.sh populates sample_genesis.json (same for pregenesis)

**Comment by IvoCrnkovic** [comment]
teddy indicates that in some cases you have to run `make update-sample-pregenesis` and commit the resulting changes after you update `genesis.sh` in [this thread](https://dydx-team.slack.com/archives/C04BNGM82HM/p1697563625631579?thread_ts=1697559168.985669&cid=C04BNGM82HM)

@teddyding for our learning can you clarify if thats required here?

**Comment by yujin512** [comment]
> teddy indicates that in some cases you have to run `make update-sample-pregenesis` and commit the resulting changes after you update `genesis.sh` in [this thread](https://dydx-team.slack.com/archives/C04BNGM82HM/p1697563625631579?thread_ts=1697559168.985669&cid=C04BNGM82HM)
> 
> @teddyding for our learning can you clarify if thats required here?
will run `make update-sample-pregenesis` and commit the resulting sample pre genesis.json in this pr https://github.com/dydxprotocol/v4-chain/pull/640

**Pull request closed without merging**
