### PR TITLE
[CT-631] choose random read replica

### PR DESCRIPTION
**Pull request by dydxwill**
### Changelist
choose random read replica

### Test Plan
tested in dev3
ran Lawrence's script polling `dydx1hhu24usgaxc9lfn879yzv2y5t64057gfwjmvz3` address

### Author/Reviewer Checklist
- [ ] If this PR has changes that result in a different app state given the same prior state and transaction list, manually add the `state-breaking` label.
- [ ] If the PR has breaking postgres changes to the indexer add the `indexer-postgres-breaking` label.
- [ ] If this PR isn't state-breaking but has changes that modify behavior in `PrepareProposal` or `ProcessProposal`, manually add the label `proposal-breaking`.
- [ ] If this PR is one of many that implement a specific feature, manually label them all `feature:[feature-name]`.
- [ ] If you wish to for mergify-bot to automatically create a PR to backport your change to a release branch, manually add the label `backport/[branch-name]`.
- [ ] Manually add any of the following labels: `refactor`, `chore`, `bug`.

### CODE REVIEW

**Comment by vincentwschau** [comment]
Did we consider just adding a route53 records to do this rather than doing it within the service? [Reference](https://repost.aws/knowledge-center/requests-rds-read-replicas)

**Review by Christopher-Li — COMMENTED** [review]
instead of doing this this, I think we should hide the read replicas behind an LB

**Comment by Christopher-Li** [comment]
actually nvm this should be fine and is less work

**Review by Christopher-Li — APPROVED** [review]

**Comment by vincentwschau** [comment]
DNS / LB I think is still preferred, since it can be changed and applied w/o a release.

**Pull request closed without merging**
